server:
  dataStorage:
    storageClass:  nfs-storage
  auditStorage:
    storageClass:  nfs-storage
  service:
    type: NodePort

# Vault UI
ui:
  enabled: true
  #serviceType: "LoadBalancer"
  serviceType: "NodePort"
  serviceNodePort: null
  externalPort: 8200

  # For Added Security, edit the below
  #loadBalancerSourceRanges:
  #   - < Your IP RANGE Ex. 10.0.0.0/16 >
  #   - < YOUR SINGLE IP Ex. 1.78.23.3/32 >
